using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace MinimalControllers.SourceGenerators.Helpers;

public class MinimalApiClassBuilder
{
    private const string ClassName = "MinimalController";
    private string _currentController = "";
    
    private readonly StringBuilder _builder = new($$"""
                                                    // <auto-generated/>
                                                    
                                                    namespace {{HttpAttributeDefinitions.Namespace}} {
                                                    
                                                        public static class {{ClassName}} {
                                                            public static WebApplication UseControllers(this WebApplication app) {
                                                            
                                                    """);

    public MinimalApiClassBuilder AddGroup(string name)
    {
        _currentController = name;
        
        _builder.AppendLine($"\tvar group = app.MapGroup(\"/{name}\");");
        return this;
    }

    public MinimalApiClassBuilder AddEndpoint(
        string httpMethod, 
        string endpoint, 
        string methodName,
        List<string> controllerServices,
        List<string> methodArguments)
    {
        
        if(string.IsNullOrEmpty(_currentController))
            throw new InvalidOperationException("You must call AddGroup before adding an endpoint.");

        var services = controllerServices.ToDictionary(
            x => x,
            x => RandomString(x)
            );

        var methodArgumentDictionary = methodArguments
            .ToDictionary(
                x => x,
                x => RandomString(x)
                );

        var combinedServices = services.Concat(methodArgumentDictionary);

        _builder.Append($$"""
                                         
                                      group.Map{{httpMethod}}("{{endpoint}}", ({{
                                          string.Join(", ", combinedServices.Select(x => $"{x.Key} {x.Value}"))
                                      }}) => {
                                          var controller = new {{
                                              _currentController
                                          }}({{
                                              string.Join(", ", services.Values)
                                          }});
                                        
                                          return controller.{{methodName}}({{
                                              string.Join(", ", methodArgumentDictionary.Values)
                                          }});
                                      });
                          """);
        return this;
    }
    
    public string Build() =>
        _builder.AppendLine("\n\t\t\treturn app;\n\t\t}\n\t}\n}").ToString();

    private static string RandomString(string input, int length = 32)
    {
        var random = new Random(Seed: input.GetHashCode());
        const string chars = "abcdefghijklmnopqrstuvwxyz";
        return new string(
            Enumerable
                .Repeat(chars, length)
            .Select(s => s[random
                    .Next(s.Length)])
                .ToArray());
    }
}