# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish .NET to Nuget

on:
  workflow_dispatch: 
    inputs: 
        version:
            description: 'Version to publish'
            required: true
            default: '0.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Publish
      run: dotnet pack MinimalControllers.SourceGenerators/MinimalControllers.SourceGenerators/MinimalControllers.SourceGenerators.csproj -o ./Output --no-build --configuration Release /p:Version=${{ github.event.inputs.version }}
    - name: Publish to Nuget
      run: dotnet nuget push ./Output/Murunu.MinimalControllers.${{ github.event.inputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}